services:
  django: &django
    image: telasttechnologies/beautycops_django:main
    container_name: django-beautycops
    networks:
      - nginx_default
    depends_on:
      - postgres
    volumes:
     - locale:/app/locale/
     - media:/app/media/
     - static:/app/static/
     - staticfiles:/app/staticfiles/
    env_file:
      - ./docker/.envs/.production/.django
      - ./docker/.envs/.production/.postgres
    command: /start

  postgres:
    image: telasttechnologies/beautycops_postgres:main
    container_name: postgres-beautycops
    networks:
      - nginx_default
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
      - ./docker/production/postgres/init-db.d/dump.sql:/docker-entrypoint-initdb.d/01_dump.sql:ro
    env_file:
      - ./docker/.envs/.production/.postgres

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  locale: {}
  media: {}
  static: {}
  staticfiles: {}

networks:
  nginx_default:
    external: true
