services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: beautycops_local_django
    container_name: beautycops_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./docker/.envs/.local/.django
      - ./docker/.envs/.local/.postgres
    environment:
      - OPENBLAS_NUM_THREADS=1
    ports:
      - "8000:8000"
    command: /start
  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: beautycops_local_postgres
    container_name: beautycops_local_postgres
    volumes:
      - beautycops_local_postgres_data:/var/lib/postgresql/data
      - beautycops_local_postgres_data_backups:/backups
      - ./docker/local/postgres/init-db.d/dump.sql:/docker-entrypoint-initdb.d/01_dump.sql:ro
    env_file:
      - ./docker/.envs/.local/.postgres

volumes:
  beautycops_local_postgres_data: {}
  beautycops_local_postgres_data_backups: {}
